# For more information about the configurations used in this file, please
# see the Travis CI documentation: https://docs.travis-ci.com

language: python
sudo: false
python:
- '3.6.4'

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -r requirements/development.txt

before_script:
- export DATABASE_URL=postgres://postgres@localhost/multi_tenant_django_application
- psql -c "CREATE DATABASE multi_tenant_django_application;" -U postgres

script:
- flake8
- pytest --cov -v --tb=native


notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
