# Generated by Django 2.1 on 2018-09-04 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('tenant_aware_suffix', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
