# Generated by Django 2.1 on 2018-09-05 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20180905_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
    ]
