# Generated by Django 2.1 on 2018-09-05 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180905_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeemodel',
            options={'ordering': ('id',), 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveField(
            model_name='employeemodel',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
    ]
